### PR TITLE
build: add graphql 16 to peer dependencies

### PR DESCRIPTION
**Pull request by elias-pap**

### CODE REVIEW

**Comment by elias-pap** [comment]
Hi @sgrove @dwwoelfel,

  I'd like to ask if this is going to be merged.

Thank you !

**Review by Gebov — APPROVED** [review]

**Comment by noelportugal** [comment]
Waiting on this merge as well 🤞

**Comment by sgrove** [comment]
@elias-pap Thank you for submitting this, just merged!

**Comment by tovbinm** [comment]
Great stuff! When is this going to be released?

**Comment by wawhal** [comment]
This is awesome! Can we expect a release sometime soon? :eyes:

**Pull request merged**
